name: KRX ETF Monitor

permissions:
  contents: write
  
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install packages
        run: pip install -r requirements_krx.txt

      - name: run script
        run: python main_krx.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: commit db
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add etf_db_krx.csv
          git diff --cached --quiet || git commit -m "update etf db krx"
          git push
